server:
  port: 9002
spring:
  application:
   name: microservice-movie
   
eureka:
  client:
  #客户端是否需要注册到Eureka
   register-with-eureka: true
   #客户端是否获取Eureka注册信息
   fetch-registry: true
   service-url: 
    defaultZone: http://127.0.0.1:8888/eureka
    #获取提供方注册信息的间隔时间
   registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true 
    #心跳间隔时间
    lease-renewal-interval-in-seconds: 10
    #续约失败时间
    lease-expiration-duration-in-seconds: 90
    
#修改负载均衡规则
microservice-user: 
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true